[workspace]
members = [
	".",
	"rorm-db",
	"rorm-declaration",
	"rorm-macro",
	"rorm-sample",
	"rorm-sql",
]

[package]
name = "rorm"
version = "0.4.0"
edition = "2021"
repository = "https://github.com/myOmikron/drorm"
authors = ["gammelalf", "myOmikron <git@omikron.dev>"]
categories = ["database"]
keywords = ["database", "orm", "async"]
description = "A asynchronous declarative ORM written in pure rust."
homepage = "https://rorm.rs"
documentation = "https://docs.rorm.rs"
license = "MIT"

[lib]
name = "rorm"
path = "src/lib.rs"

[dependencies]
# Abstractions for asynchronous programming.
futures = { version = "~0.3" }

# json serialization to communicate with the migrator
serde_json = { version = "~1.0" }

# linker magic to create a slice containing all models defined by crates
linkme = { version = "~0.3" }

# Time and date library
chrono = { version = "~0.4" }

# self referencing struct (currently JoinBuilder)
ouroboros = { version = "~0.15" }

# Allow wrapping futures and streams
pin-project = { version = "~1.0" }


rorm-db = { version = "~0.5", path = "./rorm-db" }
rorm-macro = { version = "~0.3", path = "./rorm-macro" }
rorm-declaration = { version = "~0.3", path = "./rorm-declaration" }

[package.metadata.docs.rs]
features = ["async-std-rustls"]

[features]
default = [
	"rorm-db/all-driver"
]

sqlite = ["rorm-db/sqlite"]
mysql = ["rorm-db/mysql"]
postgres = ["rorm-db/postgres"]

tokio-rustls = ["rorm-db/tokio-rustls"]
tokio-native-tls = ["rorm-db/tokio-native-tls"]

async-std-rustls = ["rorm-db/async-std-rustls"]
async-std-native-tls = ["rorm-db/async-std-native-tls"]

actix-rustls = ["rorm-db/actix-rustls"]
actix-native-tls = ["rorm-db/actix-native-tls"]

[profile.release-lto]
inherits = "release"
lto = "fat"

[profile.release-debug]
inherits = "release"
debug = true
