[Migration]
Hash = '7417045264120078121'
Initial = false
Dependency = 6
Replaces = []

[[Migration.Operations]]
Type = 'CreateModel'
Name = 'account'

[[Migration.Operations.Fields]]
Name = 'id'
Type = 'int32'

[[Migration.Operations.Fields.Annotations]]
Type = 'auto_increment'

[[Migration.Operations.Fields.Annotations]]
Type = 'primary_key'

[[Migration.Operations.Fields]]
Name = 'username'
Type = 'varchar'

[[Migration.Operations.Fields.Annotations]]
Type = 'index'

[[Migration.Operations.Fields.Annotations]]
Type = 'max_length'
Value = 255

[[Migration.Operations.Fields.Annotations]]
Type = 'unique'

[[Migration.Operations.Fields.Annotations]]
Type = 'not_null'

[[Migration.Operations.Fields]]
Name = 'superuser'
Type = 'boolean'

[[Migration.Operations.Fields.Annotations]]
Type = 'default_value'
Value = false

[[Migration.Operations.Fields.Annotations]]
Type = 'not_null'

[[Migration.Operations.Fields]]
Name = 'member_since'
Type = 'datetime'

[[Migration.Operations.Fields.Annotations]]
Type = 'auto_create_time'

[[Migration.Operations.Fields.Annotations]]
Type = 'not_null'

[[Migration.Operations.Fields]]
Name = 'gender'
Type = 'choices'

[[Migration.Operations.Fields.Annotations]]
Type = 'choices'
Value = [
    'Male',
    'Female',
    'Other',
]

[[Migration.Operations.Fields]]
Name = 'birthday'
Type = 'date'
Annotations = []

[[Migration.Operations]]
Type = 'CreateModel'
Name = 'comment'

[[Migration.Operations.Fields]]
Name = 'id'
Type = 'int32'

[[Migration.Operations.Fields.Annotations]]
Type = 'auto_increment'

[[Migration.Operations.Fields.Annotations]]
Type = 'primary_key'

[[Migration.Operations.Fields]]
Name = 'message'
Type = 'varchar'

[[Migration.Operations.Fields.Annotations]]
Type = 'max_length'
Value = 255

[[Migration.Operations.Fields.Annotations]]
Type = 'not_null'

[[Migration.Operations.Fields]]
Name = 'created'
Type = 'datetime'

[[Migration.Operations.Fields.Annotations]]
Type = 'auto_create_time'

[[Migration.Operations.Fields.Annotations]]
Type = 'not_null'

[[Migration.Operations]]
Type = 'CreateModel'
Name = 'thread'

[[Migration.Operations.Fields]]
Name = 'id'
Type = 'int32'

[[Migration.Operations.Fields.Annotations]]
Type = 'auto_increment'

[[Migration.Operations.Fields.Annotations]]
Type = 'primary_key'

[[Migration.Operations.Fields]]
Name = 'name'
Type = 'varchar'

[[Migration.Operations.Fields.Annotations]]
Type = 'max_length'
Value = 255

[[Migration.Operations.Fields.Annotations]]
Type = 'not_null'

[[Migration.Operations]]
Type = 'CreateField'
Model = 'thread'

[Migration.Operations.Field]
Name = 'creator'
Type = 'int32'

[[Migration.Operations.Field.Annotations]]
Type = 'not_null'

[[Migration.Operations.Field.Annotations]]
Type = 'foreign_key'

[Migration.Operations.Field.Annotations.Value]
TableName = 'account'
ColumnName = 'id'
OnDelete = 'Restrict'
OnUpdate = 'Restrict'

[[Migration.Operations]]
Type = 'CreateField'
Model = 'comment'

[Migration.Operations.Field]
Name = 'user'
Type = 'varchar'

[[Migration.Operations.Field.Annotations]]
Type = 'not_null'

[[Migration.Operations.Field.Annotations]]
Type = 'foreign_key'

[Migration.Operations.Field.Annotations.Value]
TableName = 'account'
ColumnName = 'username'
OnDelete = 'Cascade'
OnUpdate = 'Restrict'

[[Migration.Operations]]
Type = 'CreateField'
Model = 'comment'

[Migration.Operations.Field]
Name = 'thread'
Type = 'int32'

[[Migration.Operations.Field.Annotations]]
Type = 'not_null'

[[Migration.Operations.Field.Annotations]]
Type = 'foreign_key'

[Migration.Operations.Field.Annotations.Value]
TableName = 'thread'
ColumnName = 'id'
OnDelete = 'Cascade'
OnUpdate = 'Restrict'
