[Database]
# Valid driver types are: "MySQL", "Postgres" and "SQLite"
Driver = "SQLite"
Filename = "sqlite.db"

# -------------------------------
# Example MySQL configuration
# -------------------------------
# Name = "dbname"
# Host = "127.0.0.1"
# Port = 3306
# User = "dbuser"
# Password = "super-secure-password"

# -------------------------------
# Example Postgres configuration
# -------------------------------
# Name = "dbname"
# Host = "127.0.0.1"
# Port = 3306
# User = "dbuser"
# Password = "super-secure-password"
