[Migration]
Hash = '7006828879424352989'
Initial = false
Dependency = 2
Replaces = []

[[Migration.Operations]]
Type = 'CreateField'
Model = 'user'

[Migration.Operations.Field]
Name = 'birthday'
Type = 'int16'

[[Migration.Operations.Field.Annotations]]
Type = 'not_null'
