[package]
name = "rorm-sql"
version = "0.1.0"
edition = "2021"

[dependencies]
# SQL database abstraction
sqlx = { version = "0.6.0", features = [ "runtime-tokio-native-tls", "mysql", "sqlite", "postgres", "tls" ] }

# Runtime
tokio = { version = "1.20.0", features = ["rt", "macros"]  }

# Generic error package
anyhow = { version = "1.0" }

# serde defines (de-)serialization behaviour for structs and enums
serde = { version = "1.0", features = ["derive"] }

# Implements Eq and Order types for f64
ordered-float = { version = "2.0", features = ["serde"] }