[package]
name = "rorm-sql"
version = "0.1.0"
edition = "2021"

[dependencies]
# Generic error package
anyhow = { version = "1.0" }

# serde defines (de-)serialization behaviour for structs and enums
serde = { version = "1.0", features = ["derive"] }

# Implements Eq and Order types for f64
ordered-float = { version = "3.0", features = ["serde"] }