---
site_name: DRORM Documentation 
theme:
  name: material
  palette:
  # Palette toggle for light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    toggle:
      icon: material/toggle-switch
      name: Switch to dark mode

  # Palette toggle for dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to light mode
repo_url: https://github.com/myOmikron/drorm
edit_uri: https://github.com/myOmikron/drorm/edit/main/docs/docs/
repo_name: myOmikron/drorm
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
nav:
  - Home: index.md
  - Migrations:
    - Migrations: migrations/migrations.md
    - Make Migrations: migrations/makemigrations.md
    - Migration File Format: migrations/migration_files.md
    - Linter: migrations/linter.md
    - Internal Model Representation: migrations/internal_model_representation.md
  - DORM:
    - Getting Started: dorm/getting_started.md
    - Model Declaration: dorm/model_declaration.md
    - Associations: dorm/associations.md
  - RORM:
    - Getting Started: rorm/getting_started.md
    - Project Setup: rorm/project_setup.md
    - Model Declaration: rorm/model_declaration.md
  - Developer information:
    - Style Guidelines: developer/guidelines.md
