[package]
name = "rorm-lib"
version = "0.1.0"
edition = "2021"
keywords = ["database", "library"]
authors = ["myOmikron <git@omikron.dev>"]
categories = ["database", "development-tools.categories.ffi"]
repository = "github.com/myOmikron/drorm"

[lib]
name = "rorm"
crate-type = ["staticlib"]

[dependencies]
rorm-db = { version = "0.1.0", path = "../rorm-db" }

[features]
default = [
    "rorm-db/tokio-rustls"
]
