name: Build & Test for MacOS
on:
  push:
    paths-ignore:
      - "*.md"
  pull_request:

jobs:
  build_rs:
    name: Build & Tests on MacOS
    runs-on: macos-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"

      # When rustup is updated, it tries to replace its binary, which on Windows is somehow locked.
      # This can result in the CI failure, see: https://github.com/rust-lang/rustup/issues/3029
      - run: |
          rustup set auto-self-update disable
          rustup toolchain install stable --profile minimal

      - uses: Swatinem/rust-cache@v2

      - name: Install dependencies
        run: |
          rustup component add clippy
          cargo install clippy-sarif sarif-fmt

      - name: Build rorm with tokio-rustls
        run: cargo build -p rorm -F tokio-rustls

      - name: Build rorm with tokio-native-tls
        run: cargo build -p rorm -F tokio-native-tls

      - name: Build rorm with async-std-rustls
        run: cargo build -p rorm -F async-std-rustls

      - name: Build rorm with async-std-native-tls
        run: cargo build -p rorm -F async-std-native-tls

      - name: Build rorm with actix-rustls
        run: cargo build -p rorm -F actix-rustls

      - name: Build rorm with actix-native-tls
        run: cargo build -p rorm -F actix-native-tls

      - name: Run rust-clippy
        run: cargo clippy --workspace --message-format=json | clippy-sarif | tee rust-clippy-results.sarif | sarif-fmt
        continue-on-error: true

      - name: Upload clippy analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: rust-clippy-results.sarif
          wait-for-processing: true