name: Build & Test for MacOS
on:
  push:
    paths-ignore:
      - "*.md"
  pull_request:

jobs:
  build-macos-shared:
    name: Build rorm from scratch
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Update rust
        run: rustup update

      - name: Build rorm
        run: cargo build -F tokio-rustls

      - name: Cargo test
        run: |
          cargo test -p rorm-macro
          cargo test -F tokio-rustls

      - name: Install rust components and tools
        run: |
          rustup component add clippy
          cargo install clippy-sarif sarif-fmt

      - name: Install rorm-cli from crates.io
        run: cargo install rorm-cli
        if: ${{ github.ref_name == 'main' }}

      - name: Install rorm-cli from git
        run: |
          git clone https://github.com/rorm-orm/rorm-cli --recursive
          cargo install rorm-cli --path rorm-cli
        if: ${{ github.ref_name != 'main' }}

      - name: Execute rorm-sample with SQLite
        env:
          CONFIG_FILE: "sqlite.toml"
        run: |
          set -x
          RUST_BACKTRACE=full cargo run -- --help
          echo Config: ${CONFIG_FILE}
          rm -rvf .models.json
          rorm-cli migrate --database-config "${CONFIG_FILE}" --log-sql
          RUST_BACKTRACE=full RUST_LOG=rorm=debug cargo run -- "${CONFIG_FILE}"
        working-directory: ./rorm-sample
