name: Run Unittests
on: [push, pull_request]

jobs:
  build-lib:
    name: Build rorm-lib
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Build rorm-lib (debug)
        run: cargo build -p rorm-lib
        working-directory: ./rorm

      - name: Build rorm-lib (release)
        run: cargo build -p rorm-lib -r
        working-directory: ./rorm

      - uses: actions/upload-artifact@v3
        with:
          name: rorm-lib-${{matrix.os}}
          path: rorm/target/

  dubtest:
    needs: build-lib
    name: Dub Tests
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        dc: [dmd-latest, ldc-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: rorm-lib-${{matrix.os}}
          path: rorm/target/

      - name: Install D compiler
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.dc }}

      - name: Build rorm-lib
        run: cargo build -p rorm-lib -r
        working-directory: ./rorm

      - name: Run tests
        run: dub test
        working-directory: ./dorm

  cargotest:
    needs: build-lib
    name: Cargo Tests
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: rorm-lib-${{matrix.os}}
          path: rorm/target/

      - name: Run CLI tests
        run: cargo test -p rorm-cli
        working-directory: ./rorm

      - name: Run DB tests
        run: cargo test -p rorm-db -F tokio-rustls
        working-directory: ./rorm

      - name: Run declaration tests
        run: cargo test -p rorm-declaration
        working-directory: ./rorm

      - name: Run lib test
        run: cargo test -p rorm-lib
        working-directory: ./rorm

      - name: Run macro test
        run: cargo test -p rorm-macro
        working-directory: ./rorm

      - name: Run sql tests
        run: cargo test -p rorm-sql -F sqlite
        working-directory: ./rorm

      - name: Run root test
        run: cargo test -F tokio-rustls
        working-directory: ./rorm

  integration:
    name: Integration Tests
    needs: [dubtest, cargotest]
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        dc: [ldc-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Install D compiler
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.dc }}

      - name: Run integration tests
        run: ./run.sh
        working-directory: ./dorm/integration-tests/
